{
  "info": {
    "description": "Endpoints that are not meant to be called externally, and are generally called by the connect widget UI",
    "title": "Internal widget service endpoints",
    "version": "0.1.0"
  },
  "openapi": "3.0.0",
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "servers": [
    {
      "description": "Widget Service",
      "url": "http://localhost:8080"
    }
  ],
  "paths": {
    "/instrumentation/userId/{userId}": {
      "post": {
        "description": "This endpoint is called by the connect widget frontend and returns response headers that are saved for future requests from the connect widget",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "current_aggregator": {
                    "type": "string"
                  },
                  "current_member_guid": {
                    "type": "string"
                  },
                  "jobTypes": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "enum": [
                        "account_verification",
                        "identity_verification",
                        "transactions",
                        "transaction_history"
                      ]
                    }
                  },
                  "single_account_select": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "headers": {
              "meta": {
                "schema": {
                  "type": "object",
                  "example": {
                    "user_id": "testUserId",
                    "jobTypes": ["transactions"],
                    "scheme": "vcs",
                    "oauth_referral_source": "BROWSER",
                    "single_account_select": true,
                    "updated": true
                  }
                }
              }
            }
          }
        }
      }
    },
    "/institutions/{institutionGuid}": {
      "get": {
        "description": "Get an institution by its aggregator's ID or by the ucp id",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object"
            },
            "examples": {
              "byAggregatorInstitutionId": {
                "description": "aggregator is required if sending an aggregator's institution id",
                "value": {
                  "aggregator": "mx"
                }
              },
              "byUCPInstitutionId": {
                "description": "jobTypes is required if sending an UCP institution id",
                "value": {
                  "jobTypes": ["transactions"]
                }
              }
            }
          },
          {
            "description": "Aggregator's institution id or UCP institution id",
            "in": "path",
            "name": "institutionGuid",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "guid": "testExampleA",
                    "code": "testExampleA",
                    "name": "TestExampleA Bank",
                    "url": "https://test-example.com",
                    "logo_url": "https://universalconnectproject.org/images/ucp-logo-icon.svg",
                    "instructional_data": {},
                    "credentials": [],
                    "supports_oauth": false,
                    "aggregator": "testExampleC"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/institutions/{institutionGuid}/credentials": {
      "get": {
        "description": "List of credential objects for the institution. These are used to render authentication inputs",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "aggregator": "mx"
              }
            }
          },
          {
            "in": "path",
            "name": "institutionGuid",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [
                    {
                      "id": "testId",
                      "field_name": "fieldName",
                      "field_type": 3,
                      "label": "TestExampleC Label",
                      "guid": "testId"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/institutions/recommended": {
      "get": {
        "description": "List of recommended institutions",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "jobTypes": ["transactions"]
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [
                    {
                      "guid": "5e498f60-3496-4299-96ed-f8eb328ae8af",
                      "name": "TestExampleA Bank",
                      "url": "https://test-example.com",
                      "logo_url": "https://universalconnectproject.org/images/ucp-logo-icon.svg"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/institutions": {
      "get": {
        "description": "List of institution search results",
        "parameters": [
          {
            "in": "header",
            "name": "meta",
            "required": true,
            "schema": {
              "type": "object",
              "example": {
                "jobTypes": ["transactions"]
              }
            }
          },
          {
            "in": "query",
            "name": "search",
            "description": "Text to be searched. Can't be used with a routingNumber query",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "routingNumber",
            "description": "9 digit institution routing number. Can't be used with a search query",
            "schema": {
              "type": "number",
              "example": 111111111
            }
          },
          {
            "in": "query",
            "name": "page",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "in": "query",
            "name": "pageSize",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [
                    {
                      "guid": "5e498f60-3496-4299-96ed-f8eb328ae8af",
                      "name": "TestExampleA Bank",
                      "url": "https://test-example.com",
                      "logo_url": "https://universalconnectproject.org/images/ucp-logo-icon.svg"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}
